# Generated by Django 4.0.6 on 2022-07-20 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=250)),
                ('player1', models.CharField(max_length=250)),
                ('player1_role', models.CharField(choices=[('IGL', 'In Game Leader'), ('ASSULTER', 'Assulter'), ('SYPPORTR', 'Supporter'), ('SNIPER', 'Sniper'), ('DMR', 'DMR')], max_length=8)),
                ('player2', models.CharField(max_length=250)),
                ('player2_role', models.CharField(choices=[('IGL', 'In Game Leader'), ('ASSULTER', 'Assulter'), ('SYPPORTR', 'Supporter'), ('SNIPER', 'Sniper'), ('DMR', 'DMR')], max_length=8)),
                ('player3', models.CharField(max_length=250)),
                ('player3_role', models.CharField(choices=[('IGL', 'In Game Leader'), ('ASSULTER', 'Assulter'), ('SYPPORTR', 'Supporter'), ('SNIPER', 'Sniper'), ('DMR', 'DMR')], max_length=8)),
                ('player4', models.CharField(max_length=250)),
                ('player4_role', models.CharField(choices=[('IGL', 'In Game Leader'), ('ASSULTER', 'Assulter'), ('SYPPORTR', 'Supporter'), ('SNIPER', 'Sniper'), ('DMR', 'DMR')], max_length=8)),
                ('player5', models.CharField(blank=True, max_length=250, null=True)),
                ('player5_role', models.CharField(choices=[('IGL', 'In Game Leader'), ('ASSULTER', 'Assulter'), ('SYPPORTR', 'Supporter'), ('SNIPER', 'Sniper'), ('DMR', 'DMR')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('game', models.CharField(choices=[('BGMI', 'BGMI'), ('FREE FIRE', 'FREE FIRE'), ('CODM', 'CODM')], max_length=10)),
                ('total_no_of_teams', models.PositiveBigIntegerField(default=0)),
                ('no_of_team_players_allowed', models.PositiveBigIntegerField(default=4)),
                ('type', models.CharField(choices=[('T', 'Tournament'), ('L', 'League')], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_round', models.CharField(max_length=50)),
                ('match_number', models.PositiveBigIntegerField()),
                ('total_kills', models.PositiveBigIntegerField(default=0)),
                ('position_points', models.PositiveBigIntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
                ('winning_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=350)),
                ('date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.match')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
